CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# Increase transmission strength
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

CONFIG_ZMK_POINTING=y

CONFIG_ZMK_KEYBOARD_NAME="Sw2e3p"