manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: nathandsanta
      url-base: https://github.com/nathandsanta
    - name: sadek
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: chocofi
      remote: nathandsanta
      revision: main
    - name: zmk-fingerpunch-keyboards
      remote: sadek
    - name: vik-core
      remote: sadek
    - name: fingerpunch-controllers
      remote: sadek
  self:
    path: config